// Start - CostData.cs
using static ItemEnums;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "New Cost Data", menuName = "Cost Data")]
public class CostData : ScriptableObject
{
    [Header("Cost Data")]
    public int price;    // Currency cost of this action
    public int revenue;  // Revenue generated by this action 
    public int expense;  // Monthly expense by this action

    [Header("Item Costs")]
    public ItemData[] costItems;    // Array of ItemData for costs
    public int[] costAmounts;       // Corresponding amounts for each ItemData

    /// <summary>
    /// The item costs as a lookup.
    ///
    /// costItems and costAmounts are paired by index and authored by hand, so this reads
    /// only as far as the shorter of the two - a half-filled asset charges what it
    /// actually states rather than throwing. A repeated item accumulates instead of
    /// throwing on a duplicate key, and an empty asset simply costs nothing.
    /// </summary>
    public Dictionary<ItemData, int> GetCostItemsDictionary()
    {
        Dictionary<ItemData, int> costDict = new Dictionary<ItemData, int>();
        if (costItems == null || costAmounts == null) return costDict;

        int pairedCount = Mathf.Min(costItems.Length, costAmounts.Length);
        for (int i = 0; i < pairedCount; i++)
        {
            ItemData item = costItems[i];
            if (item == null) continue;

            int existing;
            costDict.TryGetValue(item, out existing);
            costDict[item] = existing + costAmounts[i];
        }
        return costDict;
    }
}

[System.Serializable]
public class ItemCost
{
    public ItemData item;
    public int amount;

    public ItemCost(ItemData item, int amount)
    {
        this.item = item;
        this.amount = amount;
    }
}

// End - CostData.cs