// Start - 
using static ItemEnums;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "New Cost Data", menuName = "Cost Data")]
public class CostData : ScriptableObject
{
    [Header("Cost Data")]
    public int price;    // Currency cost of this action
    public int revenue;  // Revenue generated by this action -
    public int expense;  // Monthly expense by this action

    [Header("Item Costs")]
    public ItemData[] costItems;  // Array of ItemData for costs
    public int[] costAmounts;  // Corresponding amounts for each ItemData

    public Dictionary<ItemData, int> GetCostItemsDictionary()
    {
        Dictionary<ItemData, int> costDict = new Dictionary<ItemData, int>();
        for (int i = 0; i < costItems.Length; i++)
        {
            costDict.Add(costItems[i], costAmounts[i]);
        }
        return costDict;
    }
}

[System.Serializable]
public class ItemCost
{
    public ItemData item;
    public int amount;

    public ItemCost(ItemData item, int amount)
    {
        this.item = item;
        this.amount = amount;
    }
}

// End - CostData.cs