// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSLerp

RWTexture2D<float4> Input;

RWTexture2D<float4> Result;

bool DissapearVision;
float DeltaTime;
[numthreads(8,8,1)]
void CSLerp (uint3 id : SV_DispatchThreadID)
{

	if(DissapearVision)
		Result[id.xy] = lerp(Result[id.xy],Input[id.xy],DeltaTime);
	else
		if (Input[id.xy].a>Result[id.xy].a)
			Result[id.xy]=Result[id.xy];
		else
			Result[id.xy] = lerp(Result[id.xy],Input[id.xy],DeltaTime);
}
